- name: install mysql
  yum: name={{ item }} state=installed
  with_items:
    - mysql-devel
    - mysql-server
    - mysql-utilities

- name: service start mysql
  service: name=mysqld state=started enabled=yes

